feat: Refactor CD workflow for enhanced deployment and rollback
The CD workflow has been refactored to improve deployment and rollback
logic.

Previously, the workflow applied all Kubernetes manifests and then
iterated through identified deployments for rollout status checks and
rollback. This change simplifies the process by applying a single
rendered Kubernetes file.

Key improvements:

- **Single Rendered File Application**: The workflow now applies a single
  rendered Kubernetes file specified by `K8S_RENDERED_FILE`.
- **Deployment Extraction with `yq`**: Deployment names and namespaces are
  now extracted using `yq`, providing a more robust method for identifying
  deployments for status checks and rollbacks.
- **Targeted Rollout Status**: `kubectl rollout status` is now used with
  specific deployment names and namespaces for more precise status checks.
- **Conditional Rollback**: Rollback is triggered if any deployment's
  rollout fails. In case of test failures, all deployments are rolled back.
- **Temporary Directory for Predictor Service**: The predictor service
  now includes a temporary directory mount and sets corresponding environment
  variables (`TMPDIR`, `TEMP`, `TMP`) to `/tmp`. This facilitates
  operations that might require temporary file storage.

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -78,22 +78,29 @@ jobs:
         env:
           K8S_ROLLOUT_TIMEOUT: ${{ vars.K8S_ROLLOUT_TIMEOUT }}
           K8S_RENDERED_ARTIFACTS_DIR: ${{ vars.K8S_RENDERED_ARTIFACTS_DIR }}
+          K8S_RENDERED_FILE: ${{ vars.K8S_RENDERED_FILE }}
         run: |
-          # Apply all the deployment k8s manifests
-          DEPLOYMENTS_APPLIED=()
-          for file in $K8S_RENDERED_ARTIFACTS_DIR/*; do
-              kubectl apply -f "$file"
-              if grep -q "kind: Deployment" "$file"; then
-                  DEPLOYMENTS_APPLIED+=("$file")
-              fi
-          done
+          # Apply the rendered k8s file
+          kubectl apply -f "$K8S_RENDERED_ARTIFACTS_DIR"/"$K8S_RENDERED_FILE"
 
-          # Check rollout status for all deployments
-          # with automatic rollback if any error occurred
-          for file in "${DEPLOYMENTS_APPLIED[@]}"; do
-              if ! kubectl rollout status -f "$file" --timeout=$K8S_ROLLOUT_TIMEOUT; then
-                  for rollback_file in "${DEPLOYMENTS_APPLIED[@]}"; do
-                      kubectl rollout undo -f "$rollback_file" || true
+          # Extract and export the deployment names from the
+          # rendered k8s file
+          DEPLOYMENTS_DATA=$(yq eval-all 'select(.kind == "Deployment") | \
+          .metadata.name + ":" + .metadata.namespace' \
+          "$K8S_RENDERED_ARTIFACTS_DIR"/"$K8S_RENDERED_FILE")
+          echo "DEPLOYMENTS_DATA=$DEPLOYMENTS_DATA" >> $GITHUB_ENV
+
+          # Check rollout status for all deployments with
+          # automatic rollback if one or more rollout failed
+          for item in $DEPLOYMENTS_DATA; do
+              dep_name="${item%%:*}"
+              dep_ns="${item##*:}"
+              if ! kubectl rollout status deployment "$dep_name" -n "$dep_ns" \
+              --timeout=$K8S_ROLLOUT_TIMEOUT; then
+                  for rollback_item in $DEPLOYMENTS_DATA; do
+                      r_name="${rollback_item%%:*}"
+                      r_ns="${rollback_item##*:}"
+                      kubectl rollout undo deployment "$r_name" -n "$r_ns" || true
                   done
                   exit 1
               fi
@@ -107,22 +114,16 @@ jobs:
         run: |
           export PYTHONPATH=$(pwd):$(pwd)/${{ vars.SRC_DIR }}
 
-          # Identify all deployments
-          DEPLOYMENTS=()
-          for file in $K8S_RENDERED_ARTIFACTS_DIR/*; do
-              if grep -q "kind: Deployment" "$file"; then
-                  DEPLOYMENTS+=("$file")
-              fi
-          done
-
           # Run tests and capture exit code
           pytest -v -m "${{ vars.PYTEST_MARKER }}" ${{ vars.API_TESTS_DIR }}
           TEST_EXIT_CODE=$?
 
           # Rollback all deployments if any test failed
           if [ $TEST_EXIT_CODE -ne 0 ]; then
-            for file in "${DEPLOYMENTS[@]}"; do
-                kubectl rollout undo -f "$file" || true
+            for item in $DEPLOYMENTS_DATA; do
+                dep_name="${item%%:*}"
+                dep_ns="${item##*:}"
+                kubectl rollout undo deployment "$dep_name" -n "$dep_ns" || true
             done
             exit $TEST_EXIT_CODE
           fi
