feat: Improve CI image scanning with Trivy
- Add cleanup steps for Docker and apt.
- Install Trivy before scanning.
- Build and scan each Docker image individually.
- Remove images after scanning.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -149,6 +149,11 @@ jobs:
           DAGS_HUB_REPO_OWNER: ${{ vars.DAGS_HUB_REPO_OWNER }}
           DAGS_HUB_TOKEN: ${{ vars.DAGS_HUB_TOKEN }}
         run: |
+          # Clean up
+          docker system prune -af --volumes || true
+          sudo apt-get clean
+
+          # Install Trivy
           TRIVY_LATEST_URL=$(curl -s ${{ vars.TRIVY_LATEST_RELEASE_URL }} \
             | grep ${{ vars.TRIVY_JSON_FIELD }} \
             | grep ${{ vars.TRIVY_PLATFORM }} \
@@ -156,31 +161,24 @@ jobs:
           wget $TRIVY_LATEST_URL -O ${{ vars.TRIVY_OUTPUT_FILE }}
           sudo ${{ vars.TRIVY_INSTALL_CMD }} ${{ vars.TRIVY_OUTPUT_FILE }}
 
-          echo "DEBUG: Listing all services found in docker-compose.yml:"
-          docker compose config --services
-
-          echo "DEBUG: Raw DOCKER_SERVICES variable content:"
-          echo "${{ vars.DOCKER_SERVICES }}" | cat -A
-
+          # Build and scan all the images
           readarray -t DOCKER_SERVICES_ARRAY <<< "$(echo "${{ vars.DOCKER_SERVICES }}" | tr -d '\r')"
-
           for img_name in "${DOCKER_SERVICES_ARRAY[@]}"; do
-            if [ -z "$img_name" ]; then continue; fi
-
-            echo "DEBUG: Current service in loop: '$img_name'"
-
+            # Get image
             img_name_normalized=$(echo "$img_name" | tr '_' '-')
             full_img="${{ secrets.ACR_NAME }}.azurecr.io/${img_name_normalized}:${{ github.sha }}"
 
-            echo "DEBUG: Executing build for: $img_name"
+            # Build image
             docker compose build "$img_name" --pull --no-cache
 
+            # Scan image with Trivy
             trivy image \
               --exit-code ${{ vars.TRIVY_EXIT_CODE }} \
               --severity ${{ vars.TRIVY_SEVERITY }} \
               --skip-db-update \
               "$full_img"
 
+            # Clean up
             docker rmi "$full_img" || true
             docker builder prune -af
             docker system prune -af --volumes
